import numpy as np

green = "\033[1;32m"
blue = "\033[1;34m"
yellow = "\033[1;33m"
magenta = "\033[1;35m"
red = "\033[1;31m"
white = "\033[1;37m"
gray = "\033[1;30m"
allColors = [red,blue,green,yellow,white,magenta,gray]

phat_style_1 = """
.....................................
.....................................
.....................................
......b.......A.......A.......d......
......Ob.....d8b.....d8b.....dO......
......O8b...d888b...d888b...d8O......
......OO8b.d88888b.d88888b.d88O......
......OO88V8888888V8888888V888O......
......OOO88888888888888888888OO......
......OOO88888888888888888888OO......
......OOOOO888888888888888888OO......
......OOOOOOOO888888888888888OO......
.....................................
.....................................
.....................................
"""
phat_style_2 = """
.....................................
.....................................
..................A..................
.................d8b.................
................dB88b................
...............dBBBBBb...............
..............d8888BBBb..............
.............dB8888888Bb.............
............dBBBBB888888b............
...........d88BBBBBBB8888b...........
..........d88888BBBBBBBB88b..........
.........dBB8888888BBBBBBBBb.........
........dBBBBB888888888BBBBBb........
.....................................
.....................................
"""
stripeChar = "B"
defaultBackground = "."
background_2 = "~"
background_3 = "*"
background_4 = "-"
background_5 = " "

allPartyHatStyles = [phat_style_1, phat_style_2]
allBackgroundStyles = [defaultBackground,background_5]

def CreatePartyHat(background,partyHatStyle,primaryHatColor,secondaryHatColor,backgroundColor):
    party_hat = partyHatStyle
    party_hat = primaryHatColor + partyHatStyle.replace(defaultBackground, backgroundColor + background + primaryHatColor)

    if partyHatStyle == phat_style_2: 
        party_hat = party_hat.replace(stripeChar, secondaryHatColor + stripeChar + primaryHatColor)
   
    print(party_hat)

def OpenPresent(n):
    for i in range(n):
        CreatePartyHat(np.random.choice(allBackgroundStyles),
                        np.random.choice(allPartyHatStyles),
                        np.random.choice(allColors),
                        np.random.choice(allColors),
                        np.random.choice(allColors)
                        )

OpenPresent(100)